name: Zip and Upload

on:
  push:
    branches:
      - "*"

jobs:
  zip-upload:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Zip pack
      run: |
        cd pack
        zip -r pack.zip *
        mv pack.zip ../pack.zip
        cd ..
        ls -la

    - name: Configure Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Commit and push changes
      run: |
        git add pack.zip
        git commit -m "Update texture pack"
        git push origin HEAD
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Send message to server
      run: curl -X POST -d "§a[JJsTextures] §eThe texture pack has been updated! Rejoin for the new effects!" "${{ secrets.SERVER_LISTENER }}"